apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rudder-load
  name: github-actions-eks
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: rudder-load
  name: github-actions-rolebinding
subjects:
  - kind: Group
    name: github-actions-group  # Must match the group in aws-auth
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: github-actions-eks
  apiGroup: rbac.authorization.k8s.io
